version: "3.8"

services:
  foundry-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://foundry-kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: foundry-zookeeper:2181
    depends_on:
      - foundry-zookeeper

  foundry-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    healthcheck:
          test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
          interval: 10s
          retries: 5

  my-scraper-1:
    build: ./my-scraper-1
    depends_on:
      - foundry-kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=foundry-kafka:9092

  proxy-service:
    build: ./proxy-service
    ports:
      - "8000:8000"

  # storage-service:
  #   build: ./storage-service
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: scraper_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"

  


  worker-manager:
    build: ./worker-manager
    depends_on:
      - foundry-kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ Allow control of Docker outside the container
